[package]
name = "led_api"
version = "0.1.0"
authors = ["pi"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
rocket = "0.4.5"
spidev = "0.4.0"
toml = "0.5"
serde = "1.0"
serde_derive = "1.0"
